### ISSUE TITLE
"V.R racing" and "Tempest 2000" does nothing when start is press

### ISSUE THREAD

**Issue by twarnercool2** [Yabause/yabause#60] opened 2015-08-24 18:26 UTC
The games go in-game fine, but the controls don't work.

**Comment by d356** [comment] 2016-03-26 13:17
Controls in both games should be working since e811a3544b3d819b9aaa31d9169ab46462acf7b2

**Comment by BenjaminSiskoo** [comment] 2016-03-30 13:30
Tempest 2000 works, i guess the other game works too.

**Comment by d356** [comment] 2016-04-05 20:36
Closing since both games have been confirmed to have working controls.

**Closed by d356** 2016-04-05 20:36 UTC
Labels: tested and works fine
